###
# Получить список заданий

GET https://api.msk-day.ru/puzzle/poi-task/14391be72342662f13306081dd13c699.json
content-type: application/json

###
# Отправить результат выполнения задания

POST https://api.msk-day.ru/puzzle/poi-task/14391be72342662f13306081dd13c699.json
content-type: application/json

{
  "device_id": 614,
  "task_id": 6,
  "turns": 50,
  "seconds": 100,
  "answer_id": 15
}

###
# Получить турнирную таблицу с постраничной навигацией

GET https://api.msk-day.ru/puzzle/poi-rating/14391be72342662f13306081dd13c699.json?expand=user&page=2
content-type: application/json

###
# Получить турнирную таблицу

GET https://api.msk-day.ru/puzzle/poi-rating/14391be72342662f13306081dd13c699.json?expand=user
content-type: application/json

###
# Проверка активации стенда

GET https://api.msk-day.ru/puzzle/poi-poi/14391be72342662f13306081dd13c699/check-activation.json
content-type: application/json

###